name: Check for new Neurodesk releases

on:
  schedule:
    - cron: 30 17 * * *
  workflow_dispatch:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  check_for_updates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install tbump

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install npm dependencies
        run: |
          npm install --global yarn
          yarn install
        
      - name: Check for new Neurodesk releases
        shell: bash
        run: |
          set -eux
          export NEURODESK_LATEST=$(python scripts/get_neurodesk_version.py)
          echo "neurodesk_latest=${NEURODESK_LATEST}" >> $GITHUB_ENV
          yarn set_neurodesk_version ${NEURODESK_LATEST}
      - name: Check for new TinyRange releases
        shell: bash
        run: |
          set -eux
          export TINYRANGE_LATEST=$(python scripts/get_tinyrange_version.py)
          echo "tinyrange_latest=${TINYRANGE_LATEST}" >> $GITHUB_ENV
          yarn set_tinyrange_version ${TINYRANGE_LATEST}
      - name: Create a PR if needed
        shell: bash
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          # if resulted in any change:
          export TINYRANGE_LATEST=${{ env.tinyrange_latest }}
          if [[ ! -z "$(git status --porcelain package.json)" ]]; then
            export BRANCH_NAME=update-tinyrange-to-v${TINYRANGE_LATEST}
            # this will fail if the branch already exists which means we won't have duplicate PRs
            git checkout -b "${BRANCH_NAME}"
            git config user.name "Neurodesk Desktop Bot"
            git config user.email 'neurodesk-bot@users.noreply.github.com'

            git commit . -m "Update to TinyRange v${TINYRANGE_LATEST}"

            git push --set-upstream origin "${BRANCH_NAME}"            
            hub pull-request -m "Update to TinyRange v${TINYRANGE_LATEST}" \
                -m "New TinyRange release [v${TINYRANGE_LATEST}](https://github.com/tinyrange/tinyrange/releases/tag/v${TINYRANGE_LATEST}) is available. Please review the lock file carefully.".
          fi

          export NEURODESK_LATEST=${{ env.neurodesk_latest }}
          if [[ ! -z "$(git status --porcelain neurodesktop.toml)" ]]; then
            export BRANCH_NAME=update-neurodesk-to-v${NEURODESK_LATEST}
            # this will fail if the branch already exists which means we won't have duplicate PRs
            git checkout -b "${BRANCH_NAME}"
            git config user.name "Neurodesk Desktop Bot"
            git config user.email 'neurodesk-bot@users.noreply.github.com'

            git commit . -m "Update to Neurodesk v${NEURODESK_LATEST}"

            git push --set-upstream origin "${BRANCH_NAME}"            
            sudo apt install hub      
            hub pull-request -m "Update to Neurodesk v${NEURODESK_LATEST}" \
                -m "New Neurodesk release [v${NEURODESK_LATEST}](https://github.com/NeuroDesk/neurodesk.github.io/blob/main/data/neurodesktop.toml) is available. Please review the lock file carefully.".
          fi

